# Generated by Django 4.2.10 on 2024-05-07 17:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('father_name', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='-', max_length=1)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='National Code')),
                ('address', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=15, null=True)),
                ('joined_date', models.DateTimeField(default=datetime.datetime(2024, 5, 7, 21, 9, 40, 555831))),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'accounts',
                'verbose_name_plural': 'accounts',
                'db_table': 'accounts',
            },
        ),
    ]
