# Generated by Django 4.2.10 on 2024-05-07 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'products_category',
            },
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'db_table': 'products_sub_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30, verbose_name='نام محصول')),
                ('count', models.SmallIntegerField(blank=True, default=0, verbose_name='تعداد محصول')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='قیمت محصول')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='عکس محصول')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='جزئیات محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.sub_category', verbose_name='نام دسته بندی')),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
