# Generated by Django 4.2.10 on 2024-05-07 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('subscribe_date', models.DateTimeField(default=datetime.datetime(2024, 5, 7, 21, 9, 31, 616236))),
            ],
            options={
                'db_table': 'subscribers_email',
            },
        ),
    ]
