# Generated by Django 4.2.10 on 2024-05-07 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0003_alter_subscriber_subscribe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscribe_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 7, 21, 10, 58, 589561)),
        ),
    ]
